sched/deadline: fix some more build errors
kernel/sched/deadline.c: In function 'inc_dl_tasks':
kernel/sched/deadline.c:757:2: error: implicit declaration of function 'inc_nr_running' [-Werror=implicit-function-declaration]
  inc_nr_running(rq_of_dl_rq(dl_rq));
  ^~~~~~~~~~~~~~
kernel/sched/deadline.c: In function 'dec_dl_tasks':
kernel/sched/deadline.c:772:2: error: implicit declaration of function 'dec_nr_running' [-Werror=implicit-function-declaration]
  dec_nr_running(rq_of_dl_rq(dl_rq));
  ^~~~~~~~~~~~~~

Same fix as before, inc_nr_running -> add_nr_running and dec_nr_running -> sub_nr_running per commit 32b1b2b52821cfd49f3e4edfc16502fccc214c3b, "sched, nohz: Change rq->nr_running to always use wrappers"

kernel/sched/deadline.c: In function 'pick_next_task_dl':
kernel/sched/deadline.c:1064:4: error: 'struct rq' has no member named 'post_schedule'
  rq->post_schedule = has_pushable_dl_tasks(rq);
    ^~
kernel/sched/deadline.c: At top level:
kernel/sched/deadline.c:1707:2: error: unknown field 'post_schedule' specified in initializer
  .post_schedule  = post_schedule_dl,
  ^

Fix using the logic of 899443e4dc330fb5ef3938b408aef992748f6ee4, "sched: Replace post_schedule with a balance callback list"

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>